"""
Arithmetic Example

This example demonstrates basic arithmetic operations using the stack-based VM.
It calculates (10 + 20) * 3 - 5 = 85
"""

from stackvm import VM, CodeGenerator

def main():
    # Create a new VM and code generator
    vm = VM()
    gen = CodeGenerator()
    
    # Generate bytecode for the expression: (10 + 20) * 3 - 5
    (
        gen
        .push(10)     # Push 10
        .push(20)     # Push 20
        .add()        # 10 + 20 = 30
        .push(3)      # Push 3
        .mul()        # 30 * 3 = 90
        .push(5)      # Push 5
        .sub()        # 90 - 5 = 85
        .print_()     # Print the result
        .halt()       # Stop execution
    )
    
    # Get the generated bytecode
    bytecode = gen.generate()
    
    # Print the disassembled program
    print("Generated program:")
    print(gen.dump())
    print("\nExecuting program...")
    
    # Run the program
    result = vm.execute(bytecode)
    
    print(f"Final result: {result}")

if __name__ == "__main__":
    main()
